version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: random_data
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network: